version: '3'
services:
  rancher:
    image: rancher/server:stable
    ports:
      - "8080:8080"
    environment:
      - CATTLE_DB_CATTLE_USERNAME=rancher
      - CATTLE_DB_CATTLE_PASSWORD=rancher
    volumes:
      - ./data/mysql/:/var/lib/mysql
